import { v4 as uuid } from "uuid";

export const Recipes = [
  {
    id:uuid(),
    name: "Spaghetti Bolognese",
    cuisine: "Italian",
    foodPic: "https://i.postimg.cc/cCf1vKpg/download.jpg",
    ingredients: [
      "spaghetti",
      "ground beef",
      "onion",
      "garlic",
      "tomato sauce",
      "crushed tomatoes",
      "carrot",
      "celery",
      "red wine",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Heat olive oil in a large skillet.",
      "Add diced onion, minced garlic, carrot, and celery. Sauté until tender.",
      "Add ground beef and cook until browned.",
      "Pour in red wine and simmer until reduced.",
      "Add tomato sauce and crushed tomatoes. Season with salt and pepper.",
      "Simmer for about 1 hour, stirring occasionally.",
      "Cook spaghetti according to package instructions.",
      "Serve the Bolognese sauce over cooked spaghetti.",
      "Garnish with grated Parmesan cheese, if desired.",
    ],
  },
  {
    id:uuid(),
    name: "Chicken Tikka Masala",
    cuisine: "Indian",
    foodPic: "https://i.postimg.cc/MGrpNJ0T/ctm.jpg",
    ingredients: [
      "chicken breast",
      "yogurt",
      "lemon juice",
      "ginger",
      "garlic",
      "garam masala",
      "paprika",
      "turmeric",
      "cumin",
      "coriander",
      "onion",
      "tomato",
      "cream",
      "butter",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cut chicken breast into bite-sized pieces.",
      "In a bowl, combine yogurt, lemon juice, ginger, garlic, garam masala, paprika, turmeric, cumin, coriander, salt, and pepper.",
      "Add chicken pieces to the marinade. Mix well and let it marinate for at least 1 hour.",
      "Preheat the grill or oven to medium-high heat.",
      "Skewer the marinated chicken pieces and grill or bake until cooked through, turning occasionally.",
      "In a separate pan, melt butter and sauté diced onion until golden brown.",
      "Add diced tomato and cook until soft.",
      "Stir in cream and simmer for a few minutes.",
      "Add the cooked chicken tikka to the sauce. Cook for an additional 5 minutes.",
      "Serve with rice or naan bread.",
    ],
  },
  {
    id:uuid(),
    name: "Caprese Salad",
    cuisine: "Italian",
    foodPic: "https://i.postimg.cc/RFyq6xq8/salad.jpg",
    ingredients: [
      "tomatoes",
      "fresh mozzarella",
      "fresh basil leaves",
      "extra virgin olive oil",
      "balsamic vinegar",
      "salt",
      "pepper",
    ],
    instructions: [
      "Slice tomatoes and fresh mozzarella into 1/4-inch thick slices.",
      "Arrange tomato and mozzarella slices on a serving plate, alternating them.",
      "Tuck fresh basil leaves between the tomato and mozzarella slices.",
      "Drizzle extra virgin olive oil and balsamic vinegar over the salad.",
      "Season with salt and pepper to taste.",
      "Let the salad sit for a few minutes to allow the flavors to meld.",
      "Serve and enjoy!",
    ],
  },
  {
    id:uuid(),
    name: "Chicken Stir-Fry",
    cuisine: "Asian",
    foodPic: "https://i.postimg.cc/Prq18T63/ctf.jpg",
    ingredients: [
      "chicken breast",
      "soy sauce",
      "hoisin sauce",
      "oyster sauce",
      "garlic",
      "ginger",
      "vegetable oil",
      "onion",
      "bell peppers",
      "carrots",
      "broccoli",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cut chicken breast into thin strips and marinate in a mixture of soy sauce, hoisin sauce, and oyster sauce for 15 minutes.",
      "Heat vegetable oil in a wok or large skillet over high heat.",
      "Add minced garlic and grated ginger to the hot oil, and stir-fry for a few seconds until fragrant.",
      "Add marinated chicken strips to the wok and stir-fry until cooked through.",
      "Add sliced onion, bell peppers, carrots, and broccoli florets to the wok. Stir-fry for a few minutes until the vegetables are crisp-tender.",
      "Season with salt and pepper to taste.",
      "Serve the chicken stir-fry over steamed rice or noodles.",
      "Enjoy!",
    ],
  },
  {
    id:uuid(),
    name: "Guacamole",
    cuisine: "Mexican",
    foodPic: "https://i.postimg.cc/Y9kW2HGx/guacamole.jpg",
    ingredients: [
      "avocados",
      "lime juice",
      "red onion",
      "tomato",
      "jalapeño",
      "cilantro",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cut avocados in half, remove the pit, and scoop the flesh into a bowl.",
      "Mash the avocado with a fork until desired consistency.",
      "Add lime juice to prevent browning and enhance flavor.",
      "Finely chop red onion, tomato, jalapeño (remove seeds for milder taste), and cilantro.",
      "Add the chopped ingredients to the mashed avocado.",
      "Season with salt and pepper to taste.",
      "Mix everything together until well combined.",
      "Taste and adjust seasonings if needed.",
      "Serve the guacamole with tortilla chips or as a condiment for tacos, burritos, or quesadillas.",
      "Enjoy!",
    ],
  },
  // Add three more recipes following the same object format...
];
